name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Show repository contents
        run: ls -R
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: PYTHONPATH=.pytest

      - name: Run Semgrep SAST scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/python

      - name: Run Gitleaks Secrets scan
        uses: gitleaks/gitleaks-action@v2

      - name: Build Docker image
        run: docker build -t secure-gitops-pipeline:ci .
      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: secure-gitops-pipeline:ci
          exit-code: "1"
          severity: HIGH,CRITICAL